### ISSUE TITLE
Triangle.py not working — CPython 3.6 Win10 64bit

### ISSUE THREAD

**Issue by Semnodime** [gabdube/python-vulkan-triangle#3]
I tried to launch the example
`python .\triangle.py`
```
Traceback (most recent call last):
  File ".\triangle.py", line 1693, in <module>
    main()
  File ".\triangle.py", line 1686, in main
    app = TriangleApplication()
  File ".\triangle.py", line 1626, in __init__
    Application.__init__(self)
  File ".\triangle.py", line 832, in __init__
    self.create_instance()
  File ".\triangle.py", line 291, in create_instance
    raise RuntimeError('Instance creation failed. Error code: {}'.format(result))
RuntimeError: Instance creation failed. Error code: 4294967289
```
Then I installed the VulkanSDK from [https://vulkan.lunarg.com/](https://vulkan.lunarg.com/) 
Now I get a different (OS) Error:
```
Traceback (most recent call last):
  File ".\triangle.py", line 1693, in <module>
    main()
  File ".\triangle.py", line 1686, in main
    app = TriangleApplication()
  File ".\triangle.py", line 1626, in __init__
    Application.__init__(self)
  File ".\triangle.py", line 832, in __init__
    self.create_instance()
  File ".\triangle.py", line 276, in create_instance
    result = vk.CreateInstance(byref(create_info), None, byref(instance))
OSError: exception: access violation reading 0x0000000200000001
```
Could you help me to launch your example?

**Comment by Semnodime** [comment]
I was able to get the same cause of error when running a different python vulkan wrapper:
It seems the error is generated by amdvlk64.dll at 0x00007FFF283EB461 in RAM while trying to access 0x0000000200000001

I am using an 2048MB ATI AMD Radeon HD 7800 Series (Sapphire/PCPartner)

**Comment by gabdube** [comment]
From my experience when the vulkan instance creation fails it's usually because Vulkan is not supported, but I've looked up and its seems your GPU should be fine.

Also the first error is ERROR_EXTENSION_NOT_PRESENT which is not good because the only extensions used are VK_KHR_surface & VK_KHR_win32_surface which are the extensions that enable presentation on system windows...

Try to run the vulkaninfo binary (it's installed with the SDK and should be available from the console). It  should output a huge text report with everything supported.

If this fails too, you can try to uninstall your current graphics drivers and reinstall the lastest driver available from the amd website.

**Comment by Semnodime** [comment]
Wow, fast response!

Indeed after updating/**reinstalling the AMD Driver it works nicely**, generating that beautiful triangle.

The issue has been that **the AMD tool falsely reported my driver was up to date** with the latest available version for that card. **Installing the auto-detect-driver-installer** from [AMD Support](https://support.amd.com/de-de/download) updated the whole driver, including Vulkan.

**Comment by gabdube** [comment]
Great! I'm closing this then.
